# PostgreSQL. Versions 9.3 and up are supported.
# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookmark_manager_api_development
  host: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_HOST'] %>
  username: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_USERNAME'] %>
  password: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: bookmark_manager_api_test
  host: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_HOST'] %>
  username: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_USERNAME'] %>
  password: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: bookmark_manager_api_staging
  DATABASE_URL: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_URL'] %>

production:
  <<: *default
  database: bookmark_manager_api_production
  DATABASE_URL: <%= ENV['BOOKMARK_MANAGER_API_DATABASE_URL'] %>
